name: Update Tabby files

on:
  #push:
<<<<<<< HEAD
  #  paths:
  #    - 'params/VERSION'
=======
    #paths:
    #  - 'params/VERSION'
>>>>>>> 7f7eddb1c8dcfc01b32d095d21e3b15e20ff95c5
  workflow_dispatch:

jobs:
  update-tabby:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get current version
        id: current_version
        run: echo ::set-output name=version::$(curl https://cdn.githubraw.com/the-alpaka/docker_tabby/main/params/VERSION)

      - name: Get latest Tabby files
        run: mkdir -p root/config/defaults/tabby && git clone -b v${{ steps.latest.outputs.version }} https://github.com/bertvandepoel/tabby.git root/config/defaults/tabby

      - name: Push updates files to Github
        uses: test-room-7/action-update-file@v1
        with:
            file-path: root/defaults/tabby
            commit-msg: bot update
            github-token: ${{ secrets.GITHUB_TOKEN }}
