name: Update Tabby files

on:
  #push:
  #  paths:
  #   - 'params/VERSION'
  workflow_dispatch:

jobs:
  update-tabby:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get current version
        id: latest
        run: echo ::set-output name=version::$(cat params/VERSION)

      - name: Clear and prepare directory
        run: rm -rf root/defaults/tabby && mkdir -p root/defaults/tabby

      - name: Get latest Tabby files
        run: git clone -b v${{ steps.latest.outputs.version }} https://github.com/bertvandepoel/tabby.git root/defaults/tabby 
      
      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "<>"

      - name: Commit changes
        run: |
          git add . 
          git commit -am 'bot update'
          git push
