name: Update Tabby files

on:
  #push:
  #  paths:
  #    - 'params/VERSION'
  workflow_dispatch:

jobs:
  update-tabby:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get current version
        id: latest
        run: echo ::set-output name=version::$(curl https://raw.githubusercontent.com/the-alpaka/docker_tabby/main/params/VERSION)

      - name: Get latest Tabby files
        run: git clone -b v${{ steps.latest.outputs.version }} https://github.com/bertvandepoel/tabby.git

      - name: Update files
        run: git clone https://github.com/the-alpaka/docker_tabby.git && rm -r docker_tabby/root/defaults/tabby && mv tabby docker_tabby/root/defaults
      
      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "<>"

      - name: Commit Changes
        run: |
          cd docker_tabby
          git add .
          git commit -am 'bot update'
          git push

      #- name: Push updates files to Github
      #  uses: test-room-7/action-update-file@v1
      #  with:
      #      file-path: root/defaults/tabby
      #      commit-msg: bot update
      #      github-token: ${{ secrets.GITHUB_TOKEN }}
