name: Log latest release
on:
  schedule:
    - cron: '* 0 * * *'
  workflow_dispatch:

jobs:
  logLatestRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.1.0
        id: get_latest_release
        with:
          route: GET /repos/{owner}/{repo}/releases/latest
          owner: bertvandepoel
          repo: tabby
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo latest release: ${{ steps.get_latest_release.outputs.data }}"