name: Log latest release
on:
  workflow_dispatch:

jobs:
  logLatestRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.1.0
        id: get_latest_release
        with:
          route: GET /repos/bertvandepoel/tabby/releases/latest
          owner: octokit
          repo: request-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo latest release: ${{ steps.get_latest_release.outputs.data }} > params/VERSION"